### ISSUE TITLE
Admin users assign roles

### ISSUE THREAD

**Issue by jcdesimp** [andymeneely/dev-fortress-server#2]
* The backend should check that user is an admin before allowing roles to be modified.
* This should be done via a middleware.

**Comment by DanSwtmn** [comment]
In Authentication.js in Middleware added a tokenErrorHandler function for the verifyToken JWT lib function

**Comment by ShaydeNofziger** [comment]
Two API tests as of now for testing with an admin user and a non admin user

**Comment by ShaydeNofziger** [comment]
Depends on andymeneely/dev-fortress-server#3
