### ISSUE TITLE
Professor shall be able to create Teams associated with a Game (server)

### ISSUE THREAD

**Issue by ShaydeNofziger** [andymeneely/dev-fortress-server#21]
Standard model / controller / CRU operations

Includes generation of unique link code for game

**Comment by ShaydeNofziger** [comment]
@jcdesimp Should the unique link be stored as a value in the `team` table, or should it be able to be calculated based on existing info?

**Comment by ShaydeNofziger** [comment]
Update model to add a "# devCaps objective" the team must reach be end of `max_rounds`

**Comment by chtinahow** [comment]
Any time a team is returned, return team type with team response.
